// Generated by Melange
'use strict';

var Test_client_drag$Buckle = require("./test_client_drag.bs.js");
var Test_client_counter$Buckle = require("./test_client_counter.bs.js");
var Test_client_http_task$Buckle = require("./test_client_http_task.bs.js");
var Test_client_btn_update_span$Buckle = require("./test_client_btn_update_span.bs.js");
var Test_client_on_with_options$Buckle = require("./test_client_on_with_options.bs.js");
var Test_client_attribute_removal$Buckle = require("./test_client_attribute_removal.bs.js");
var Test_client_counter_debug_program$Buckle = require("./test_client_counter_debug_program.bs.js");
var Test_client_counter_debug_beginner$Buckle = require("./test_client_counter_debug_beginner.bs.js");
var Test_client_counter_debug_standard$Buckle = require("./test_client_counter_debug_standard.bs.js");

var counter = Test_client_counter$Buckle.main;

var counter_debug_beginner = Test_client_counter_debug_beginner$Buckle.main;

var counter_debug_standard = Test_client_counter_debug_standard$Buckle.main;

var counter_debug_program = Test_client_counter_debug_program$Buckle.main;

var btn_update_span = Test_client_btn_update_span$Buckle.main;

var attribute_removal = Test_client_attribute_removal$Buckle.main;

var drag = Test_client_drag$Buckle.main;

var on_with_options = Test_client_on_with_options$Buckle.main;

var http_task = Test_client_http_task$Buckle.main;

exports.counter = counter;
exports.counter_debug_beginner = counter_debug_beginner;
exports.counter_debug_standard = counter_debug_standard;
exports.counter_debug_program = counter_debug_program;
exports.btn_update_span = btn_update_span;
exports.attribute_removal = attribute_removal;
exports.drag = drag;
exports.on_with_options = on_with_options;
exports.http_task = http_task;
/* Test_client_drag-Buckle Not a pure module */
