// Generated by Melange
'use strict';

var Tea_app = require("bucklescript-tea/./src-ocaml/tea_app.bs.js");
var Tea_html = require("bucklescript-tea/./src-ocaml/tea_html.bs.js");

function update$p(model, param) {
  return [
          model[0],
          "right"
        ];
}

function render_model(param) {
  if (param[0] !== undefined && param[1] !== undefined) {
    return Tea_html.input$p(undefined, undefined, {
                hd: Tea_html.value("This should be on screen"),
                tl: /* [] */0
              }, /* [] */0);
  }
  return Tea_html.span(undefined, undefined, /* [] */0, {
              hd: Tea_html.text("nothing"),
              tl: /* [] */0
            });
}

function view$p(model) {
  return Tea_html.div(undefined, undefined, /* [] */0, {
              hd: Tea_html.button(undefined, undefined, {
                    hd: Tea_html.onClick(/* Trigger */0),
                    tl: /* [] */0
                  }, {
                    hd: Tea_html.text("trigger rerender"),
                    tl: /* [] */0
                  }),
              tl: {
                hd: render_model(model),
                tl: /* [] */0
              }
            });
}

var partial_arg_model = [
  "left",
  undefined
];

var partial_arg = {
  model: partial_arg_model,
  update: update$p,
  view: view$p
};

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

var trigger = /* Trigger */0;

exports.trigger = trigger;
exports.update$p = update$p;
exports.render_model = render_model;
exports.view$p = view$p;
exports.main = main;
/* Tea_html Not a pure module */
