// Generated by Melange
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Tea_app = require("bucklescript-tea/./src-ocaml/tea_app.bs.js");
var Tea_json = require("bucklescript-tea/./src-ocaml/tea_json.bs.js");
var Tea_html2 = require("bucklescript-tea/./src-ocaml/tea_html2.bs.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function set_value(param_0) {
  return /* Set_value */{
          _0: param_0
        };
}

function update(model, n) {
  if (n) {
    return n._0;
  } else {
    return model + 1 | 0;
  }
}

function view(model) {
  var clientX = Tea_json.Decoder.field("clientX", Tea_json.Decoder.$$int);
  var init = Tea_html2.Events.defaultOptions;
  return Tea_html2.div(undefined, undefined, /* [] */0, List.map((function (e) {
                    return Tea_html2.div(undefined, undefined, /* [] */0, {
                                hd: e,
                                tl: /* [] */0
                              });
                  }), {
                  hd: Tea_html2.text(String(model)),
                  tl: {
                    hd: Tea_html2.button(undefined, undefined, {
                          hd: Tea_html2.Events.onClick(/* Click */0),
                          tl: /* [] */0
                        }, {
                          hd: Tea_html2.text("onClick"),
                          tl: /* [] */0
                        }),
                    tl: {
                      hd: Tea_html2.button(undefined, undefined, {
                            hd: Curry._3(Tea_html2.Events.on, "", "click", Tea_json.Decoder.succeed(/* Click */0)),
                            tl: /* [] */0
                          }, {
                            hd: Tea_html2.text("on \"click\""),
                            tl: /* [] */0
                          }),
                      tl: {
                        hd: Tea_html2.a(undefined, undefined, {
                              hd: Tea_html2.Attributes.href("https://www.google.com"),
                              tl: /* [] */0
                            }, {
                              hd: Tea_html2.text("a normal link"),
                              tl: /* [] */0
                            }),
                        tl: {
                          hd: Tea_html2.a(undefined, undefined, {
                                hd: Tea_html2.Attributes.href("https://www.google.com"),
                                tl: {
                                  hd: Curry._4(Tea_html2.Events.onWithOptions, "", "click", {
                                        stopPropagation: init.stopPropagation,
                                        preventDefault: true
                                      }, Tea_json.Decoder.succeed(/* Click */0)),
                                  tl: /* [] */0
                                }
                              }, {
                                hd: Tea_html2.text("a link with prevent default"),
                                tl: /* [] */0
                              }),
                          tl: {
                            hd: Tea_html2.button(undefined, undefined, {
                                  hd: Curry._3(Tea_html2.Events.on, "", "click", Tea_json.Decoder.map(set_value, clientX)),
                                  tl: /* [] */0
                                }, {
                                  hd: Tea_html2.text("on \"click\", use clientX value"),
                                  tl: /* [] */0
                                }),
                            tl: {
                              hd: Tea_html2.input$p(undefined, undefined, {
                                    hd: Tea_html2.Attributes.type$p("text"),
                                    tl: {
                                      hd: Curry._3(Tea_html2.Events.on, "", "input", Tea_json.Decoder.map((function (v) {
                                                  return /* Set_value */{
                                                          _0: Caml_format.caml_int_of_string(v)
                                                        };
                                                }), Tea_html2.Events.targetValue)),
                                      tl: /* [] */0
                                    }
                                  }, /* [] */0),
                              tl: /* [] */0
                            }
                          }
                        }
                      }
                    }
                  }
                }));
}

var partial_arg = {
  model: 0,
  update: update,
  view: view
};

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

var click = /* Click */0;

exports.click = click;
exports.set_value = set_value;
exports.update = update;
exports.view = view;
exports.main = main;
/* Tea_json Not a pure module */
